config/routes.rb
Rails.application.routes.draw do
  resources :user_sessions, only: [:create, :new, :destroy]
  resources :users do
    member do
      get :follow
      post :follow
    end
  end
  resources :posts
  resources :follows, only: [:destroy]
  root 'posts#index'
end

app/models/follow.rb
class Follow < ActiveRecord::Base

  extend ActsAsFollower::FollowerLib
  extend ActsAsFollower::FollowScopes

  # NOTE: Follows belong to the "followable" interface, and also to followers
  belongs_to :followable, :polymorphic => true
  belongs_to :follower,   :polymorphic => true

  def block!
    self.update_attribute(:blocked, true)
  end

end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user

  def self.sort_by_users
    Post.all.sort_by{|x| x.users.count}.reverse
  end

  def self.timeline(user)
    following_ids = user.all_following.map(&:id)
    all_ids= following_ids << user.id
    Post.where(user_id: all_ids).order("created_at DESC")
  end

  validates :message, presence: true, length: {maximum: 170}
  validates :user_id, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base

  acts_as_followable
  acts_as_follower

  acts_as_authentic do |c|
    c.login_field :username
    c.validate_password_field = false

  end

  has_many :posts

  end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user_session, :current_user
  before_action :current_user

  private

  def current_user_session
    return @current_user_session if defined?(@current_user_session)
    @current_user_session = UserSession.find
  end

  def current_user
    return @current_user if defined?(@current_user)
    @current_user = current_user_session && current_user_session.user
  end

  def require_user
    unless @current_user
      flash[:danger] = "Please log in."
      redirect_to root_path
    end
  end

  def require_no_user
    if @current_user
      flash[:warning] = "Thanks for logging in!"
      redirect_to root_path
    end
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def new
    @follow = current_user.follows.new(params[:follower_id])
  end

  def create
    @follow = current_user.follows.new(params[:follower_id])
    if @follow.save
      flash[:notice] = "Followed"
      redirect_to root_path
    else
      flash[:notice] = "Follow unsuccessful"
      redirect_to root_path
    end
  end

  def destroy
    @user = User.find(params[:id])
    @current_user.stop_following(@user)
    flash[:notice] = "Unfollowed!"
    redirect_to root_path
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    if @current_user
      @posts= Post.timeline(@current_user).page(params[:page]).per(10)
    else
      @posts = Post.order("created_at DESC").page(params[:page]).per(10)
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = @current_user
      if @post.save
        flash[:success] = "Thanks for sharing!"
        redirect_to root_path
      else
        flash[:notice] = "Message failed to save."
        render :new
      end
    end

  private

  def post_params
    params.require(:post).permit(:user, :message)
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  before_action :require_no_user, only: [:new, :create]
  before_action :require_user, only: [:destroy]

  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(params[:user_session])
    if @user_session.save
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    @current_user_session.destroy
    flash[:notice] = "See you later!"
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_no_user, :only => [:new, :create]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.active = true
    @user.approved = true
    @user.confirmed = true
    if @user.save
      flash[:notice] = "Thanks for signing up!"
      redirect_to root_path
    else
      render :new
    end
  end

  def follow
    @user = User.find(params[:id])
    if current_user
      current_user.follow(@user)
      redirect_to root_path
    else
      flash[:notice] = "Please log in to follow other users."
      redirect_to root_path
    end
  end

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/models_helper.rb
module ModelsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Twitterchen</title>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name %>
    <% end %>

<%= yield %>

</body>
</html>

app/views/models/new.html.erb
<h1>New Model</h1>

<%= render 'form' %>

<%= link_to 'Back', models_path %>

app/views/posts/index.html.erb
<div class="container">
  <h1>Twitterchen</h1>
</div>
<div class="container-fluid" style="float: right">
  <% if @current_user %>
    <%= button_to "Post", new_post_path, :class => "btn btn-primary", method: :get %>
    <%= button_to "Log out", user_session_path(@current_user), :class => "btn btn-primary", method: :delete %>
  <% else %>
    <%= button_to "Log in", new_user_session_path, :class => "btn btn-primary", method: :get %>
    <%= button_to "Sign up", new_user_path, :class => "btn btn-primary", method: :get %>
  <% end %>
</div>
  <%= render "shared/index" %>
<br>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for(@post) do |x| %>
  <div class="form-group">
    <%= x.label "What're you up to?", :id => "new_post_label" %>
    <%= x.text_area :message, :class => "form-control", :rows => 5 %>
  </div>
  <div class="form-group">
    <%= x.submit "Save" %>
  </div>

<% end %>

app/views/posts/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>


<p>

  <strong>More posts by</strong>
  <%= link_to "#{@post.user.username}", user_path(@post.user.id) %>

</p>

<p>
  <strong>Message:</strong>
  <%= @post.message %>
  <p>Posted on <%= @post.created_at.strftime('%b %e, %l:%M %p') %></p>
</p>

<%= link_to 'Back', root_path %>

app/views/shared/_index.html.erb
<div class="container">
  <table class="table">
    <tbody>
      <% @posts.each do |post| %>
      <tr class="table-row">
        <td><%= link_to "#{post.user.username}",user_path(post.user.id) %> said: </td>
        <td><%= post.message %></td>
        <td><%= link_to "Show", post %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<%= paginate @posts %>
<%= page_entries_info @posts %>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<div class="container">
  <%= form_for @user_session do |x| %>
  <% if @user_session.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user_session.errors.count, "error") %> prohibited:</h2>
    <ul>
      <% @user_session.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
    <p>Username:</p>
      <%= x.text_field :username %>
    <p>Password:</p>
      <%= x.password_field :password %>
    <%= x.submit "Login" %>
  <% end %>
</div>
<div class= "container">
  <%= link_to "Home", root_path %>
</div>

app/views/users/new.html.erb
<h1>Create an account:</h1>

<div class="container">
  <%= form_for @user do |x| %>
    <p>Username:</p>
      <%= x.text_field :username %>
    <p>Email:</p>
      <%= x.email_field :email %>
    <p>Password:</p>
      <%= x.password_field :password %>
    <p>Confirm password:</p>
      <%= x.password_field :password_confirmation %>
    <%= x.submit "Submit" %>
  <% end %>
</div>
<div class= "container">
  <%= link_to "Home", root_path %>
</div>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<%= link_to "Home", root_path %>

<div class="container" style="float: right; margin-right: 30px;">
  <h3>Followers</h3>
  <% if @user.followers != nil %>
  <ul>
    <% @user.followers.each do |x| %>
      <li><%= x.username %></li>
    <% end %>
  </ul>
  <% end %>
</div>
<br>
<% if @current_user %>
  <% if @current_user.following?(@user) %>
    <%= button_to "Unfollow", follow_path(@user), :class => "btn btn-primary", method: :delete %>
    <% else %>
    <%= button_to "Follow", follow_user_path, :class => "btn btn-primary", :remote => true %>
  <% end %>
<% end %>
<br>
<div class="container">
  <table class="table">
      <tbody>
        <% @user.posts.each do |post| %>
        <tr class="table-row">
          <td><%= post.message %></td>
          <td><small>Posted on <%= post.created_at.strftime('%b %e, %l:%M %p') %></small></td>
        </tr>
        <% end %>
      </tbody>
  </table>
</div>